
export const FETCH_CHATS_FAILURE = 'FETCH_CHATS_FAILURE'
export const FETCH_CHATS_REQUEST = 'FETCH_CHATS_REQUEST'
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS'

export const SET_CHATS = 'SET_CHATS'
export const ADD_CHAT = 'ADD_CHAT'
export const UPDATE_LAST_USED = 'UPDATE_LAST_USED'
export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const REMOVE_CHAT = 'REMOVE_CHAT'
export const DELETE_CHAT = 'DELETE_CHAT'
export const LOAD_HISTORY = 'LOAD_HISTORY'
export const UPDATE_CHAT = 'UPDATE_CHAT'
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
