platform :ios, '17.4'

require File.join(File.dirname(`node -p "require.resolve('react-native/scripts/react_native_pods.rb')"`), 'react_native_pods')
require 'json'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AIxplore' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => false # 禁用 Fabric
  )

  # 引入 react-native-permissions 的 setup 脚本
  require_relative '../node_modules/react-native-permissions/scripts/setup'

  # 配置需要的权限
  setup_permissions([
    'Camera',          # 摄像头权限
    'PhotoLibrary',    # 照片库权限
    'Microphone',      # 麦克风权限（如果需要）
    # 其他权限可以根据需要添加
  ])

  # React Native Maps 配置
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  # Google Sign-In 配置
  pod 'GoogleSignIn', '~> 7.1'

  target 'AIxploreTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # 修复 M1/M2 芯片模拟器问题
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
